import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto py-4 px-2">
        <h1 className="font-bold text-6xl">
          Welcome to{" "}
          <a
            href="/"
            className="text-transparent bg-gradient-to-tr from-blue-500 to-purple-500 bg-clip-text"
          >
            FineLine!
          </a>Deploy
        </h1>

        <p className="">when the ___ is ___</p>

        <div className="grid grid-cols-2 gap-4 my-4">
          <a href="https://nextjs.org/docs" className="">
            <Card>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </Card>
          </a>

          <a href="https://nextjs.org/learn" className="">
            <Card>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </Card>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className=""
          >
            <Card>
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </Card>
          </a>

          <a
            href="/simulator"
            className=""
          >
            <Card>
              <h2>Financial Simulator &rarr;</h2>
              <p>
                Try our fun financial life simulator if you dare! &rarr;
              </p>
            </Card>
          </a>
          <a
            href="/fines"
            className=""
          >
            <Card>
              <h2>Fines &rarr;</h2>
              <p>
                This is the fun police! &rarr;
              </p>
            </Card>
          </a>
        </div>
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
